"""Enhanced PowerPoint report generator matching HTML report structure"""
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from typing import Dict, Any
from datetime import datetime
import io

class PPTReportGenerator:
    """Generate comprehensive PowerPoint presentations matching HTML report structure"""
    
    @staticmethod
    def get_grade_color(grade: str) -> tuple:
        """Get RGB color for grade"""
        grade = grade.upper().replace('+', '')
        if grade in ['A', 'APLUS']:
            return (5, 150, 105)  # Green
        elif grade in ['B', 'BPLUS']:
            return (217, 119, 6)  # Orange
        else:
            return (220, 38, 38)  # Red
    
    @staticmethod
    def add_title_slide(prs, title_text, subtitle_text):
        """Add a title slide"""
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        title.text = title_text
        subtitle.text = subtitle_text
        
        return slide
    
    @staticmethod
    def add_section_slide(prs, title_text, content_items):
        """Add a section slide with bullet points"""
        bullet_slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = title_text
        tf = body_shape.text_frame
        tf.clear()
        
        for item in content_items:
            if isinstance(item, dict):
                p = tf.add_paragraph() if tf.paragraphs[0].text else tf.paragraphs[0]
                p.text = item.get('text', '')
                p.level = item.get('level', 0)
                if item.get('bold'):
                    p.font.bold = True
            else:
                p = tf.add_paragraph() if tf.paragraphs[0].text else tf.paragraphs[0]
                p.text = str(item)
        
        return slide
    
    @staticmethod
    def generate_jmeter_ppt_report(metrics: Dict[str, Any]) -> bytes:
        """Generate a comprehensive PowerPoint report matching HTML structure"""
        
        prs = Presentation()
        prs.slide_width = Inches(10)
        prs.slide_height = Inches(7.5)
        
        # Extract all metrics
        summary = metrics.get("summary", {})
        overall_grade = summary.get("overall_grade", "N/A")
        overall_score = summary.get("overall_score", 0)
        success_rate = summary.get("success_rate", 0)
        
        sample_time = metrics.get("sample_time", {})
        avg_response = sample_time.get("mean", 0) / 1000
        p70 = sample_time.get("p70", 0) / 1000
        p80 = sample_time.get("p80", 0) / 1000
        p90 = sample_time.get("p90", 0) / 1000
        p95 = sample_time.get("p95", 0) / 1000
        p99 = sample_time.get("p99", 0) / 1000
        median = sample_time.get("median", 0) / 1000
        max_time = sample_time.get("max", 0) / 1000
        
        error_rate = metrics.get("error_rate", 0) * 100
        throughput = metrics.get("throughput", 0)
        total_samples = metrics.get("total_samples", 0)
        test_duration = summary.get("test_duration_hours", 0)
        
        sla_2s = summary.get("sla_compliance_2s", 0)
        sla_3s = summary.get("sla_compliance_3s", 0)
        sla_5s = summary.get("sla_compliance_5s", 0)
        
        grade_reasons = summary.get("grade_reasons", {})
        overall_grade_description = summary.get("overall_grade_description", {})
        critical_issues = summary.get("critical_issues", [])
        recommendations = summary.get("recommendations", [])
        improvement_roadmap = summary.get("improvement_roadmap", [])
        transaction_stats = summary.get("transaction_stats", {})
        request_stats = summary.get("request_stats", {})
        
        scores = summary.get("scores", {})
        
        current_date = datetime.now().strftime("%B %d, %Y")
        
        # ==================== SLIDE 1: TITLE ====================
        PPTReportGenerator.add_title_slide(
            prs,
            "Performance Assessment Report",
            f"Load Testing Results & Executive Analysis\\n{current_date}\\nGenerated By: Raghvendra Kumar"
        )
        
        # ==================== SLIDE 2: EXECUTIVE SUMMARY ====================
        exec_items = [
            {"text": f"Overall Grade: {overall_grade} ({overall_score:.0f}/100)", "level": 0, "bold": True},
            {"text": f"Success Rate: {success_rate:.1f}%", "level": 1},
            {"text": f"Avg Response Time: {avg_response:.2f}s", "level": 1},
            {"text": f"Error Rate: {error_rate:.2f}%", "level": 1},
            {"text": f"Throughput: {throughput:.1f} req/s", "level": 1},
            {"text": "", "level": 0},
            {"text": f"Total Requests: {total_samples:,}", "level": 0},
            {"text": f"Test Duration: {test_duration:.2f} hours", "level": 0},
        ]
        PPTReportGenerator.add_section_slide(prs, "📊 Executive Summary", exec_items)
        
        # ==================== SLIDE 3: PERFORMANCE SCORECARD ====================
        blank_slide_layout = prs.slide_layouts[6]
        slide = prs.slides.add_slide(blank_slide_layout)
        
        # Add title
        title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(9), Inches(0.6))
        title_frame = title_box.text_frame
        title_frame.text = "🎯 Performance Scorecard & Grading"
        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(32)
        title_para.font.bold = True
        title_para.font.color.rgb = RGBColor(37, 99, 235)
        
        # Add grade display with one-liner
        grade_title = overall_grade_description.get("title", "Performance Assessment")
        grade_range = overall_grade_description.get("score_range", "")
        
        grade_box = slide.shapes.add_textbox(Inches(2), Inches(1.0), Inches(6), Inches(0.6))
        grade_frame = grade_box.text_frame
        grade_frame.text = f"OVERALL GRADE: {overall_grade}"
        grade_para = grade_frame.paragraphs[0]
        grade_para.alignment = PP_ALIGN.CENTER
        grade_para.font.size = Pt(36)
        grade_para.font.bold = True
        grade_color = PPTReportGenerator.get_grade_color(overall_grade)
        grade_para.font.color.rgb = RGBColor(*grade_color)
        
        # Grade title (one-liner meaning)
        title_desc_box = slide.shapes.add_textbox(Inches(2), Inches(1.65), Inches(6), Inches(0.4))
        title_desc_frame = title_desc_box.text_frame
        title_desc_frame.text = grade_title
        title_desc_para = title_desc_frame.paragraphs[0]
        title_desc_para.alignment = PP_ALIGN.CENTER
        title_desc_para.font.size = Pt(16)
        title_desc_para.font.bold = True
        
        score_box = slide.shapes.add_textbox(Inches(2), Inches(2.1), Inches(6), Inches(0.3))
        score_frame = score_box.text_frame
        score_frame.text = f"Score: {overall_score:.0f}/100 | Range: {grade_range}"
        score_para = score_frame.paragraphs[0]
        score_para.alignment = PP_ALIGN.CENTER
        score_para.font.size = Pt(12)
        
        # Helper for grade one-liners
        def get_grade_one_liner(cat_grade):
            one_liners = {
                "A+": "Exceptional", "A": "Excellent", "B+": "Good", "B": "Above Avg",
                "C+": "Average", "C": "Below Avg", "D": "Poor", "F": "Failing"
            }
            return one_liners.get(cat_grade, "N/A")
        
        # Add scorecard table
        rows = 5
        cols = 5
        left = Inches(0.3)
        top = Inches(2.6)
        width = Inches(9.4)
        height = Inches(2.5)
        
        table = slide.shapes.add_table(rows, cols, left, top, width, height).table
        
        table.columns[0].width = Inches(2.2)
        table.columns[1].width = Inches(0.7)
        table.columns[2].width = Inches(1.0)
        table.columns[3].width = Inches(0.6)
        table.columns[4].width = Inches(4.9)
        
        # Header
        table.cell(0, 0).text = "Category"
        table.cell(0, 1).text = "Grade"
        table.cell(0, 2).text = "Status"
        table.cell(0, 3).text = "Score"
        table.cell(0, 4).text = "Metrics"
        
        # Data
        categories = [
            ("performance", "Performance"),
            ("reliability", "Reliability"),
            ("user_experience", "User Experience"),
            ("scalability", "Scalability")
        ]
        
        for i, (cat_key, cat_name) in enumerate(categories, 1):
            gr = grade_reasons.get(cat_key, {})
            icon = gr.get("icon", "")
            weight = gr.get("weight", "")
            cat_grade = gr.get("grade", "N/A")
            table.cell(i, 0).text = f"{icon} {cat_name} ({weight})"
            table.cell(i, 1).text = cat_grade
            table.cell(i, 2).text = get_grade_one_liner(cat_grade)
            table.cell(i, 3).text = f"{gr.get('score', 0):.0f}"
            table.cell(i, 4).text = gr.get("reason", "N/A")
        
        # Style header row
        for j in range(5):
            cell = table.cell(0, j)
            cell.fill.solid()
            cell.fill.fore_color.rgb = RGBColor(37, 99, 235)
            for paragraph in cell.text_frame.paragraphs:
                for run in paragraph.runs:
                    run.font.color.rgb = RGBColor(255, 255, 255)
                    run.font.bold = True
                    run.font.size = Pt(10)
        
        # Style grade column (bold)
        for i in range(1, 5):
            cell = table.cell(i, 1)
            for paragraph in cell.text_frame.paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True
                    run.font.size = Pt(14)
        
        # ==================== SLIDE: CATEGORY SUMMARY ====================
        desc_slide = prs.slides.add_slide(blank_slide_layout)
        
        # Title
        title_box = desc_slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(9), Inches(0.6))
        title_frame = title_box.text_frame
        title_frame.text = "📖 Category Summary"
        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(28)
        title_para.font.bold = True
        title_para.font.color.rgb = RGBColor(37, 99, 235)
        
        # Category cards - 2x2 grid
        card_positions = [
            (0.3, 1.2), (5.0, 1.2),
            (0.3, 4.2), (5.0, 4.2)
        ]
        
        for idx, (cat_key, cat_name) in enumerate(categories):
            gr = grade_reasons.get(cat_key, {})
            icon = gr.get("icon", "")
            weight = gr.get("weight", "")
            cat_grade = gr.get("grade", "N/A")
            score = gr.get("score", 0)
            reason = gr.get("reason", "N/A")
            
            x, y = card_positions[idx]
            
            # Card box
            card_box = desc_slide.shapes.add_textbox(Inches(x), Inches(y), Inches(4.5), Inches(2.8))
            card_frame = card_box.text_frame
            card_frame.word_wrap = True
            
            # Grade at top
            p1 = card_frame.paragraphs[0]
            p1.text = f"{cat_grade}"
            p1.font.size = Pt(36)
            p1.font.bold = True
            p1.alignment = PP_ALIGN.CENTER
            grade_rgb = PPTReportGenerator.get_grade_color(cat_grade)
            p1.font.color.rgb = RGBColor(*grade_rgb)
            
            # One-liner
            p2 = card_frame.add_paragraph()
            p2.text = get_grade_one_liner(cat_grade)
            p2.font.size = Pt(11)
            p2.alignment = PP_ALIGN.CENTER
            
            # Category name
            p3 = card_frame.add_paragraph()
            p3.text = f"{icon} {cat_name} ({weight})"
            p3.font.size = Pt(14)
            p3.font.bold = True
            p3.space_before = Pt(10)
            
            # Score
            p4 = card_frame.add_paragraph()
            p4.text = f"Score: {score:.0f}/100"
            p4.font.size = Pt(10)
            
            # Metrics
            p5 = card_frame.add_paragraph()
            p5.text = reason
            p5.font.size = Pt(9)
            p5.space_before = Pt(5)
        
        # ==================== SLIDE 4: GRADING METHODOLOGY ====================
        method_items = [
            {"text": "Performance Grading Scale:", "level": 0, "bold": True},
            {"text": "A+ (90-100): Exceptional - Industry leading", "level": 1},
            {"text": "A (80-89): Excellent - Exceeds standards", "level": 1},
            {"text": "B+ (75-79): Good - Meets standards", "level": 1},
            {"text": "B (70-74): Acceptable - Minor improvements", "level": 1},
            {"text": "C+ (65-69): Marginal - Significant issues", "level": 1},
            {"text": "D (50-59): Critical - Immediate action", "level": 1},
            {"text": "", "level": 0},
            {"text": "Weighted Scoring Formula:", "level": 0, "bold": True},
            {"text": "Performance: 30%", "level": 1},
            {"text": "Reliability: 25%", "level": 1},
            {"text": "User Experience: 25%", "level": 1},
            {"text": "Scalability: 20%", "level": 1},
        ]
        PPTReportGenerator.add_section_slide(prs, "📏 Grading Methodology", method_items)
        
        # ==================== SLIDE 5: TEST OVERVIEW ====================
        test_items = [
            {"text": f"Total Requests: {total_samples:,}", "level": 0},
            {"text": f"Test Duration: {test_duration:.2f} hours", "level": 0},
            {"text": f"Average Throughput: {throughput:.1f} req/s", "level": 0},
            {"text": "", "level": 0},
            {"text": "Response Time Statistics:", "level": 0, "bold": True},
            {"text": f"Median: {median:.2f}s", "level": 1},
            {"text": f"70th Percentile: {p70:.2f}s", "level": 1},
            {"text": f"90th Percentile: {p90:.2f}s", "level": 1},
            {"text": f"95th Percentile: {p95:.2f}s", "level": 1},
            {"text": f"99th Percentile: {p99:.2f}s", "level": 1},
            {"text": f"Maximum: {max_time:.2f}s", "level": 1},
        ]
        PPTReportGenerator.add_section_slide(prs, "📊 Test Overview", test_items)
        
        # ==================== SLIDE 6: PERFORMANCE TABLES ====================
        slide = prs.slides.add_slide(blank_slide_layout)
        
        # Title
        title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(9), Inches(0.5))
        title_frame = title_box.text_frame
        title_frame.text = "📊 Performance Summary - Top Slowest"
        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(28)
        title_para.font.bold = True
        title_para.font.color.rgb = RGBColor(37, 99, 235)
        
        # Transaction table
        if transaction_stats:
            sorted_trans = sorted(transaction_stats.items(), 
                                 key=lambda x: x[1].get('avg_response', 0) or 0, 
                                 reverse=True)[:5]
            
            rows_trans = len(sorted_trans) + 1
            trans_table = slide.shapes.add_table(rows_trans, 4, Inches(0.5), Inches(1), Inches(9), Inches(2.5)).table
            
            # Headers
            headers = ["Transaction", "Avg Time", "95th %ile", "Error %"]
            for j, header in enumerate(headers):
                trans_table.cell(0, j).text = header
                cell = trans_table.cell(0, j)
                cell.fill.solid()
                cell.fill.fore_color.rgb = RGBColor(37, 99, 235)
                for paragraph in cell.text_frame.paragraphs:
                    for run in paragraph.runs:
                        run.font.color.rgb = RGBColor(255, 255, 255)
                        run.font.bold = True
                        run.font.size = Pt(10)
            
            # Data
            for i, (label, data) in enumerate(sorted_trans, 1):
                trans_table.cell(i, 0).text = label[:35]
                trans_table.cell(i, 1).text = f"{data.get('avg_response', 0)/1000:.2f}s"
                trans_table.cell(i, 2).text = f"{data.get('p95', 0)/1000:.2f}s"
                trans_table.cell(i, 3).text = f"{data.get('error_rate', 0):.2f}%"
                
                # Set font size
                for j in range(4):
                    for paragraph in trans_table.cell(i, j).text_frame.paragraphs:
                        for run in paragraph.runs:
                            run.font.size = Pt(9)
        
        # Request table
        if request_stats:
            sorted_req = sorted(request_stats.items(), 
                               key=lambda x: x[1].get('avg_response', 0) or 0, 
                               reverse=True)[:5]
            
            rows_req = len(sorted_req) + 1
            req_table = slide.shapes.add_table(rows_req, 4, Inches(0.5), Inches(4), Inches(9), Inches(2.5)).table
            
            # Headers
            for j, header in enumerate(headers):
                req_table.cell(0, j).text = header if j == 0 else headers[j]
                cell = req_table.cell(0, j)
                cell.fill.solid()
                cell.fill.fore_color.rgb = RGBColor(5, 150, 105)
                for paragraph in cell.text_frame.paragraphs:
                    for run in paragraph.runs:
                        run.font.color.rgb = RGBColor(255, 255, 255)
                        run.font.bold = True
                        run.font.size = Pt(10)
            
            # Data
            for i, (label, data) in enumerate(sorted_req, 1):
                req_table.cell(i, 0).text = label[:35]
                req_table.cell(i, 1).text = f"{data.get('avg_response', 0)/1000:.2f}s"
                req_table.cell(i, 2).text = f"{data.get('p95', 0)/1000:.2f}s"
                req_table.cell(i, 3).text = f"{data.get('error_rate', 0):.2f}%"
                
                for j in range(4):
                    for paragraph in req_table.cell(i, j).text_frame.paragraphs:
                        for run in paragraph.runs:
                            run.font.size = Pt(9)
        
        # ==================== SLIDE 7: CRITICAL ISSUES ====================
        if critical_issues:
            issue_items = [
                {"text": f"IMMEDIATE ACTION REQUIRED: {len(critical_issues)} critical issue(s) identified", 
                 "level": 0, "bold": True}
            ]
            
            for i, issue in enumerate(critical_issues[:4], 1):
                issue_items.append({"text": "", "level": 0})
                issue_items.append({"text": f"Issue #{i}: {issue.get('title', 'Unknown')}", "level": 0, "bold": True})
                issue_items.append({"text": f"Impact: {issue.get('impact', 'N/A')[:100]}", "level": 1})
                issue_items.append({"text": f"Priority: {issue.get('priority', 'N/A')} | Timeline: {issue.get('timeline', 'N/A')}", "level": 1})
            
            PPTReportGenerator.add_section_slide(prs, "🔴 Critical Issues", issue_items)
        
        # ==================== SLIDE 8: PATH TO IMPROVE ====================
        if improvement_roadmap:
            improve_items = []
            for phase in improvement_roadmap[:3]:
                improve_items.append({"text": f"{phase.get('phase', 'Phase')}", "level": 0, "bold": True})
                improve_items.append({"text": f"Timeline: {phase.get('timeline', 'TBD')}", "level": 1})
                improve_items.append({"text": f"Target: {phase.get('target_grade', 'N/A')}", "level": 1})
                improve_items.append({"text": f"Impact: {phase.get('expected_impact', 'N/A')}", "level": 1})
                improve_items.append({"text": "", "level": 0})
            
            PPTReportGenerator.add_section_slide(prs, "🎯 Path to A+ Grade", improve_items)
        
        # ==================== SLIDE 9: BUSINESS IMPACT ====================
        business_items = [
            {"text": "Business Impact Assessment", "level": 0, "bold": True},
            {"text": "Investment Required: Significant (6 months)", "level": 1},
            {"text": "Timeline to A+: 6 Months", "level": 1},
            {"text": "Expected ROI: High (First year)", "level": 1},
            {"text": "Payback Period: 2-4 Months", "level": 1},
            {"text": "", "level": 0},
            {"text": "Cost of Inaction:", "level": 0, "bold": True},
            {"text": f"Error Rate ({error_rate:.2f}%): {'Major' if error_rate > 5 else 'Moderate'} revenue loss", "level": 1},
            {"text": f"Performance ({avg_response:.1f}s): {'Significant' if avg_response > 5 else 'Moderate'} productivity loss", "level": 1},
            {"text": "User Abandonment: High opportunity cost", "level": 1},
        ]
        PPTReportGenerator.add_section_slide(prs, "💰 Business Impact", business_items)
        
        # ==================== SLIDE 10: RECOMMENDED ACTION PLAN ====================
        action_items = [
            {"text": "Three-Phase Improvement Approach:", "level": 0, "bold": True},
            {"text": "", "level": 0},
            {"text": "Phase 1: Critical Fixes (Week 1-4)", "level": 0, "bold": True},
            {"text": "Fix critical bugs and errors", "level": 1},
            {"text": "Optimize slowest endpoints", "level": 1},
            {"text": "Implement basic caching", "level": 1},
            {"text": "", "level": 0},
            {"text": "Phase 2: Performance Optimization (Week 4-12)", "level": 0, "bold": True},
            {"text": "Database optimization", "level": 1},
            {"text": "Redis caching implementation", "level": 1},
            {"text": "API optimization", "level": 1},
            {"text": "", "level": 0},
            {"text": "Phase 3: Excellence (Week 12-24)", "level": 0, "bold": True},
            {"text": "High availability architecture", "level": 1},
            {"text": "Advanced monitoring", "level": 1},
        ]
        PPTReportGenerator.add_section_slide(prs, "🚀 Recommended Action Plan", action_items)
        
        # ==================== SLIDE 11: SUCCESS METRICS ====================
        slide = prs.slides.add_slide(blank_slide_layout)
        
        # Title
        title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(9), Inches(0.5))
        title_frame = title_box.text_frame
        title_frame.text = "🎯 Success Metrics & Targets"
        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(28)
        title_para.font.bold = True
        title_para.font.color.rgb = RGBColor(37, 99, 235)
        
        # Targets table
        rows = 7
        cols = 4
        table = slide.shapes.add_table(rows, cols, Inches(0.5), Inches(1.2), Inches(9), Inches(5)).table
        
        table.columns[0].width = Inches(2.5)
        table.columns[1].width = Inches(2)
        table.columns[2].width = Inches(2)
        table.columns[3].width = Inches(2.5)
        
        # Header
        headers = ["Metric", "Current", "6-Month Target", "Industry Std"]
        for j, header in enumerate(headers):
            table.cell(0, j).text = header
            cell = table.cell(0, j)
            cell.fill.solid()
            cell.fill.fore_color.rgb = RGBColor(37, 99, 235)
            for paragraph in cell.text_frame.paragraphs:
                for run in paragraph.runs:
                    run.font.color.rgb = RGBColor(255, 255, 255)
                    run.font.bold = True
        
        # Data
        target_data = [
            ["Avg Response", f"{avg_response:.1f}s", f"{max(0.8, avg_response*0.3):.1f}s", "<2s"],
            ["95th Percentile", f"{p95:.1f}s", f"{max(2.5, p95*0.2):.1f}s", "<3s"],
            ["Error Rate", f"{error_rate:.2f}%", "0.3%", "<0.5%"],
            ["Success Rate", f"{success_rate:.1f}%", "99.5%", ">99%"],
            ["SLA Compliance", f"{sla_2s:.1f}%", "95%", ">95%"],
            ["Throughput", f"{throughput:.0f}/s", f"{max(180, throughput*2.5):.0f}/s", "150/s"],
        ]
        
        for i, row_data in enumerate(target_data, 1):
            for j, cell_data in enumerate(row_data):
                table.cell(i, j).text = cell_data
        
        # ==================== SLIDE 12: RECOMMENDATIONS ====================
        if recommendations:
            rec_items = []
            for rec in recommendations[:3]:
                rec_items.append({"text": rec.get("category", "General"), "level": 0, "bold": True})
                rec_items.append({"text": f"Priority: {rec.get('priority', 'N/A')}", "level": 1})
                items = rec.get("items", [])
                for item in items[:3]:
                    rec_items.append({"text": item, "level": 2})
                rec_items.append({"text": "", "level": 0})
            
            PPTReportGenerator.add_section_slide(prs, "💡 Recommendations", rec_items)
        
        # ==================== SLIDE 13: NEXT STEPS & FOOTER ====================
        next_items = [
            {"text": "Immediate Actions Required:", "level": 0, "bold": True},
            {"text": "Executive approval of action plan", "level": 1},
            {"text": "Resource allocation (engineers, budget)", "level": 1},
            {"text": "Production deployment strategy", "level": 1},
            {"text": "Weekly progress review schedule", "level": 1},
            {"text": "", "level": 0},
            {"text": "Reporting Schedule:", "level": 0, "bold": True},
            {"text": "Daily: Critical fix progress", "level": 1},
            {"text": "Weekly: Performance metrics review", "level": 1},
            {"text": "Monthly: Business impact assessment", "level": 1},
            {"text": "", "level": 0},
            {"text": f"Report Generated: {current_date}", "level": 0},
            {"text": "Generated By: Raghvendra Kumar", "level": 0},
            {"text": "Classification: Internal", "level": 0},
        ]
        PPTReportGenerator.add_section_slide(prs, "📞 Next Steps & Contacts", next_items)
        
        # Save to BytesIO
        buffer = io.BytesIO()
        prs.save(buffer)
        buffer.seek(0)
        
        return buffer.getvalue()
    
    @staticmethod
    def generate_web_vitals_ppt_report(metrics: Dict[str, Any], filename: str = "web_vitals_report") -> bytes:
        """Generate PowerPoint report for Web Vitals metrics"""
        prs = Presentation()
        prs.slide_width = Inches(10)
        prs.slide_height = Inches(7.5)
        
        current_date = datetime.now().strftime("%B %d, %Y")
        total_samples = metrics.get("total_samples", 0)
        
        lcp = metrics.get("lcp", {})
        fid = metrics.get("fid", {})
        cls_data = metrics.get("cls", {})
        fcp = metrics.get("fcp", {})
        ttfb = metrics.get("ttfb", {})
        summary = metrics.get("summary", {})
        
        # Title Slide
        PPTReportGenerator.add_title_slide(prs, "⚡ Web Vitals Performance Report", f"Core Web Vitals Analysis\n{current_date}\nSamples: {total_samples:,}")
        
        # Summary Slide
        lcp_mean = lcp.get('mean', 0) or 0
        fid_mean = fid.get('mean', 0) or 0
        cls_mean = cls_data.get('mean', 0) or 0
        fcp_mean = fcp.get('mean', 0) or 0
        ttfb_mean = ttfb.get('mean', 0) or 0
        
        summary_items = [
            {"text": "Core Web Vitals Metrics:", "level": 0, "bold": True},
            {"text": f"LCP (Largest Contentful Paint): {lcp_mean:.0f}ms {'✅ Good' if lcp_mean <= 2500 else '⚠️ Needs Work' if lcp_mean <= 4000 else '❌ Poor'}", "level": 1},
            {"text": f"FID (First Input Delay): {fid_mean:.0f}ms {'✅ Good' if fid_mean <= 100 else '⚠️ Needs Work' if fid_mean <= 300 else '❌ Poor'}", "level": 1},
            {"text": f"CLS (Cumulative Layout Shift): {cls_mean:.3f} {'✅ Good' if cls_mean <= 0.1 else '⚠️ Needs Work' if cls_mean <= 0.25 else '❌ Poor'}", "level": 1},
            {"text": f"FCP (First Contentful Paint): {fcp_mean:.0f}ms {'✅ Good' if fcp_mean <= 1800 else '⚠️ Needs Work' if fcp_mean <= 3000 else '❌ Poor'}", "level": 1},
            {"text": f"TTFB (Time to First Byte): {ttfb_mean:.0f}ms {'✅ Good' if ttfb_mean <= 800 else '⚠️ Needs Work' if ttfb_mean <= 1800 else '❌ Poor'}", "level": 1},
            {"text": "", "level": 0},
            {"text": "Performance Distribution:", "level": 0, "bold": True},
            {"text": f"LCP: {summary.get('lcp_good', 0)} Good, {summary.get('lcp_needs_improvement', 0)} Needs Improvement, {summary.get('lcp_poor', 0)} Poor", "level": 1},
            {"text": f"FID: {summary.get('fid_good', 0)} Good, {summary.get('fid_needs_improvement', 0)} Needs Improvement, {summary.get('fid_poor', 0)} Poor", "level": 1},
            {"text": f"CLS: {summary.get('cls_good', 0)} Good, {summary.get('cls_needs_improvement', 0)} Needs Improvement, {summary.get('cls_poor', 0)} Poor", "level": 1},
        ]
        PPTReportGenerator.add_section_slide(prs, "📊 Web Vitals Summary", summary_items)
        
        # Recommendations Slide
        rec_items = [
            {"text": "Recommendations:", "level": 0, "bold": True},
            {"text": "Optimize LCP: Improve server response time, use CDN, optimize images", "level": 1},
            {"text": "Reduce FID: Minimize JavaScript execution time, use web workers", "level": 1},
            {"text": "Improve CLS: Set explicit sizes for images/videos, avoid inserting content above existing content", "level": 1},
            {"text": "", "level": 0},
            {"text": f"Report Generated: {current_date}", "level": 0},
            {"text": "Generated By: Raghvendra Kumar", "level": 0},
        ]
        PPTReportGenerator.add_section_slide(prs, "🚀 Recommendations", rec_items)
        
        # Save
        buffer = io.BytesIO()
        prs.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()
    
    @staticmethod
    def generate_ui_performance_ppt_report(metrics: Dict[str, Any], filename: str = "ui_performance_report") -> bytes:
        """Generate PowerPoint report for UI Performance metrics"""
        prs = Presentation()
        prs.slide_width = Inches(10)
        prs.slide_height = Inches(7.5)
        
        current_date = datetime.now().strftime("%B %d, %Y")
        total_samples = metrics.get("total_samples", 0)
        
        dns = metrics.get("dns_lookup_time", {})
        conn = metrics.get("connection_time", {})
        ssl = metrics.get("ssl_time", {})
        ttfb = metrics.get("time_to_first_byte", {})
        download = metrics.get("content_download_time", {})
        dom = metrics.get("dom_processing_time", {})
        page_load = metrics.get("page_load_time", {})
        full_load = metrics.get("full_page_load_time", {})
        
        # Title Slide
        PPTReportGenerator.add_title_slide(prs, "🎯 UI Performance Report", f"Page Load Timing Analysis\n{current_date}\nSamples: {total_samples:,}")
        
        # Summary Slide
        summary_items = [
            {"text": "Page Load Timing Metrics (Average):", "level": 0, "bold": True},
            {"text": f"DNS Lookup: {dns.get('mean', 0) or 0:.0f}ms", "level": 1},
            {"text": f"Connection Time: {conn.get('mean', 0) or 0:.0f}ms", "level": 1},
            {"text": f"SSL/TLS Time: {ssl.get('mean', 0) or 0:.0f}ms", "level": 1},
            {"text": f"Time to First Byte: {ttfb.get('mean', 0) or 0:.0f}ms", "level": 1},
            {"text": f"Content Download: {download.get('mean', 0) or 0:.0f}ms", "level": 1},
            {"text": f"DOM Processing: {dom.get('mean', 0) or 0:.0f}ms", "level": 1},
            {"text": f"Page Load Time: {page_load.get('mean', 0) or 0:.0f}ms", "level": 1},
            {"text": f"Full Page Load: {full_load.get('mean', 0) or 0:.0f}ms", "level": 1},
        ]
        PPTReportGenerator.add_section_slide(prs, "📊 Performance Summary", summary_items)
        
        # P95 Metrics Slide
        p95_items = [
            {"text": "95th Percentile Metrics:", "level": 0, "bold": True},
            {"text": f"DNS Lookup: {dns.get('p95', 0) or 0:.0f}ms", "level": 1},
            {"text": f"Connection Time: {conn.get('p95', 0) or 0:.0f}ms", "level": 1},
            {"text": f"Time to First Byte: {ttfb.get('p95', 0) or 0:.0f}ms", "level": 1},
            {"text": f"Page Load Time: {page_load.get('p95', 0) or 0:.0f}ms", "level": 1},
            {"text": f"Full Page Load: {full_load.get('p95', 0) or 0:.0f}ms", "level": 1},
            {"text": "", "level": 0},
            {"text": f"Report Generated: {current_date}", "level": 0},
            {"text": "Generated By: Raghvendra Kumar", "level": 0},
        ]
        PPTReportGenerator.add_section_slide(prs, "📈 95th Percentile Analysis", p95_items)
        
        # Save
        buffer = io.BytesIO()
        prs.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()
